---
# This playbook prints a simple debug message
- name: Echo 
  hosts: all
  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: Sleep
    ansible.builtin.pause:
      minutes: 3
  - name: Shell port test
    ansible.builtin.shell:
      cmd: |
        timeout 3 bash -c 'cat </dev/null >/dev/tcp/route53.amazonaws.com/443'
        echo $?
  - name: Test Route53
    ansible.builtin.uri:
      url: https://route53.amazonaws.com
  - name: Dump environment
    ansible.builtin.shell:
      cmd: |
        echo $AWS_CONFIG
        cat $AWS_CONFIG
  - name: Sleep
    ansible.builtin.pause:
      minutes: 10
