---
# This playbook prints a simple debug message
- name: Echo 
  hosts: all
  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: Dump environment
    ansible.builtin.shell:
      cmd: |
        echo $AWS_CONFIG
        cat $AWS_CONFIG
  - name: Sleep
    ansible.builtin.pause:
      minutes: 10
