---
# This playbook prints a simple debug message
- name: Echo 
  hosts: all
  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: Dump environment
    ansible.builtin.command:
      cmd: env | sort
  - name: Sleep
    ansible.builtin.pause:
      minutes: 10
